spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect

eb:
    security:
        cors:
            allowed-origins:
                - http://localhost:5173
            allowed-methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowed-headers:
                - "*"
            allow-credentials: true
        http:
            permit-all-paths:
                - /auth/**
                - /h2-console/**
                - /public/*
        jwt:
            secret: 
            expiration-ms: 86400000